/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SellerRouteImport } from './routes/seller'
import { Route as SellRouteImport } from './routes/sell'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SellerIndexRouteImport } from './routes/seller.index'
import { Route as MessagesIndexRouteImport } from './routes/messages.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as SellerOrdersRouteImport } from './routes/seller.orders'
import { Route as SellerNewRouteImport } from './routes/seller.new'
import { Route as SellerKycRouteImport } from './routes/seller.kyc'
import { Route as SellerUsernameRouteImport } from './routes/seller.$username'
import { Route as MessagesConversationIdRouteImport } from './routes/messages.$conversationId'
import { Route as ListingSlugRouteImport } from './routes/listing.$slug'
import { Route as LegalTermsRouteImport } from './routes/legal.terms'
import { Route as LegalSellerAgreementRouteImport } from './routes/legal.seller-agreement'
import { Route as LegalRefundRouteImport } from './routes/legal.refund'
import { Route as LegalPrivacyRouteImport } from './routes/legal.privacy'
import { Route as LegalDisclaimerRouteImport } from './routes/legal.disclaimer'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'
import { Route as AdminPaymentsRouteImport } from './routes/admin.payments'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminKycRouteImport } from './routes/admin.kyc'
import { Route as ApiPublicRazorpayWebhookRouteImport } from './routes/api.public.razorpay-webhook'
import { Route as AdminOrdersOrderIdRouteImport } from './routes/admin.orders.$orderId'
import { Route as AccountOrdersOrderIdRouteImport } from './routes/account.orders.$orderId'

const SellerRoute = SellerRouteImport.update({
  id: '/seller',
  path: '/seller',
  getParentRoute: () => rootRouteImport,
} as any)
const SellRoute = SellRouteImport.update({
  id: '/sell',
  path: '/sell',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerIndexRoute = SellerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SellerRoute,
} as any)
const MessagesIndexRoute = MessagesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MessagesRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const SellerOrdersRoute = SellerOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => SellerRoute,
} as any)
const SellerNewRoute = SellerNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => SellerRoute,
} as any)
const SellerKycRoute = SellerKycRouteImport.update({
  id: '/kyc',
  path: '/kyc',
  getParentRoute: () => SellerRoute,
} as any)
const SellerUsernameRoute = SellerUsernameRouteImport.update({
  id: '/$username',
  path: '/$username',
  getParentRoute: () => SellerRoute,
} as any)
const MessagesConversationIdRoute = MessagesConversationIdRouteImport.update({
  id: '/$conversationId',
  path: '/$conversationId',
  getParentRoute: () => MessagesRoute,
} as any)
const ListingSlugRoute = ListingSlugRouteImport.update({
  id: '/listing/$slug',
  path: '/listing/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalSellerAgreementRoute = LegalSellerAgreementRouteImport.update({
  id: '/legal/seller-agreement',
  path: '/legal/seller-agreement',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRefundRoute = LegalRefundRouteImport.update({
  id: '/legal/refund',
  path: '/legal/refund',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalDisclaimerRoute = LegalDisclaimerRouteImport.update({
  id: '/legal/disclaimer',
  path: '/legal/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminKycRoute = AdminKycRouteImport.update({
  id: '/kyc',
  path: '/kyc',
  getParentRoute: () => AdminRoute,
} as any)
const ApiPublicRazorpayWebhookRoute =
  ApiPublicRazorpayWebhookRouteImport.update({
    id: '/api/public/razorpay-webhook',
    path: '/api/public/razorpay-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminOrdersOrderIdRoute = AdminOrdersOrderIdRouteImport.update({
  id: '/$orderId',
  path: '/$orderId',
  getParentRoute: () => AdminOrdersRoute,
} as any)
const AccountOrdersOrderIdRoute = AccountOrdersOrderIdRouteImport.update({
  id: '/orders/$orderId',
  path: '/orders/$orderId',
  getParentRoute: () => AccountRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/marketplace': typeof MarketplaceRoute
  '/messages': typeof MessagesRouteWithChildren
  '/sell': typeof SellRoute
  '/seller': typeof SellerRouteWithChildren
  '/admin/kyc': typeof AdminKycRoute
  '/admin/orders': typeof AdminOrdersRouteWithChildren
  '/admin/payments': typeof AdminPaymentsRoute
  '/category/$slug': typeof CategorySlugRoute
  '/legal/disclaimer': typeof LegalDisclaimerRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/refund': typeof LegalRefundRoute
  '/legal/seller-agreement': typeof LegalSellerAgreementRoute
  '/legal/terms': typeof LegalTermsRoute
  '/listing/$slug': typeof ListingSlugRoute
  '/messages/$conversationId': typeof MessagesConversationIdRoute
  '/seller/$username': typeof SellerUsernameRoute
  '/seller/kyc': typeof SellerKycRoute
  '/seller/new': typeof SellerNewRoute
  '/seller/orders': typeof SellerOrdersRoute
  '/admin/': typeof AdminIndexRoute
  '/messages/': typeof MessagesIndexRoute
  '/seller/': typeof SellerIndexRoute
  '/account/orders/$orderId': typeof AccountOrdersOrderIdRoute
  '/admin/orders/$orderId': typeof AdminOrdersOrderIdRoute
  '/api/public/razorpay-webhook': typeof ApiPublicRazorpayWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRouteWithChildren
  '/auth': typeof AuthRoute
  '/marketplace': typeof MarketplaceRoute
  '/sell': typeof SellRoute
  '/admin/kyc': typeof AdminKycRoute
  '/admin/orders': typeof AdminOrdersRouteWithChildren
  '/admin/payments': typeof AdminPaymentsRoute
  '/category/$slug': typeof CategorySlugRoute
  '/legal/disclaimer': typeof LegalDisclaimerRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/refund': typeof LegalRefundRoute
  '/legal/seller-agreement': typeof LegalSellerAgreementRoute
  '/legal/terms': typeof LegalTermsRoute
  '/listing/$slug': typeof ListingSlugRoute
  '/messages/$conversationId': typeof MessagesConversationIdRoute
  '/seller/$username': typeof SellerUsernameRoute
  '/seller/kyc': typeof SellerKycRoute
  '/seller/new': typeof SellerNewRoute
  '/seller/orders': typeof SellerOrdersRoute
  '/admin': typeof AdminIndexRoute
  '/messages': typeof MessagesIndexRoute
  '/seller': typeof SellerIndexRoute
  '/account/orders/$orderId': typeof AccountOrdersOrderIdRoute
  '/admin/orders/$orderId': typeof AdminOrdersOrderIdRoute
  '/api/public/razorpay-webhook': typeof ApiPublicRazorpayWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/marketplace': typeof MarketplaceRoute
  '/messages': typeof MessagesRouteWithChildren
  '/sell': typeof SellRoute
  '/seller': typeof SellerRouteWithChildren
  '/admin/kyc': typeof AdminKycRoute
  '/admin/orders': typeof AdminOrdersRouteWithChildren
  '/admin/payments': typeof AdminPaymentsRoute
  '/category/$slug': typeof CategorySlugRoute
  '/legal/disclaimer': typeof LegalDisclaimerRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/refund': typeof LegalRefundRoute
  '/legal/seller-agreement': typeof LegalSellerAgreementRoute
  '/legal/terms': typeof LegalTermsRoute
  '/listing/$slug': typeof ListingSlugRoute
  '/messages/$conversationId': typeof MessagesConversationIdRoute
  '/seller/$username': typeof SellerUsernameRoute
  '/seller/kyc': typeof SellerKycRoute
  '/seller/new': typeof SellerNewRoute
  '/seller/orders': typeof SellerOrdersRoute
  '/admin/': typeof AdminIndexRoute
  '/messages/': typeof MessagesIndexRoute
  '/seller/': typeof SellerIndexRoute
  '/account/orders/$orderId': typeof AccountOrdersOrderIdRoute
  '/admin/orders/$orderId': typeof AdminOrdersOrderIdRoute
  '/api/public/razorpay-webhook': typeof ApiPublicRazorpayWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/auth'
    | '/marketplace'
    | '/messages'
    | '/sell'
    | '/seller'
    | '/admin/kyc'
    | '/admin/orders'
    | '/admin/payments'
    | '/category/$slug'
    | '/legal/disclaimer'
    | '/legal/privacy'
    | '/legal/refund'
    | '/legal/seller-agreement'
    | '/legal/terms'
    | '/listing/$slug'
    | '/messages/$conversationId'
    | '/seller/$username'
    | '/seller/kyc'
    | '/seller/new'
    | '/seller/orders'
    | '/admin/'
    | '/messages/'
    | '/seller/'
    | '/account/orders/$orderId'
    | '/admin/orders/$orderId'
    | '/api/public/razorpay-webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/account'
    | '/auth'
    | '/marketplace'
    | '/sell'
    | '/admin/kyc'
    | '/admin/orders'
    | '/admin/payments'
    | '/category/$slug'
    | '/legal/disclaimer'
    | '/legal/privacy'
    | '/legal/refund'
    | '/legal/seller-agreement'
    | '/legal/terms'
    | '/listing/$slug'
    | '/messages/$conversationId'
    | '/seller/$username'
    | '/seller/kyc'
    | '/seller/new'
    | '/seller/orders'
    | '/admin'
    | '/messages'
    | '/seller'
    | '/account/orders/$orderId'
    | '/admin/orders/$orderId'
    | '/api/public/razorpay-webhook'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/auth'
    | '/marketplace'
    | '/messages'
    | '/sell'
    | '/seller'
    | '/admin/kyc'
    | '/admin/orders'
    | '/admin/payments'
    | '/category/$slug'
    | '/legal/disclaimer'
    | '/legal/privacy'
    | '/legal/refund'
    | '/legal/seller-agreement'
    | '/legal/terms'
    | '/listing/$slug'
    | '/messages/$conversationId'
    | '/seller/$username'
    | '/seller/kyc'
    | '/seller/new'
    | '/seller/orders'
    | '/admin/'
    | '/messages/'
    | '/seller/'
    | '/account/orders/$orderId'
    | '/admin/orders/$orderId'
    | '/api/public/razorpay-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  MarketplaceRoute: typeof MarketplaceRoute
  MessagesRoute: typeof MessagesRouteWithChildren
  SellRoute: typeof SellRoute
  SellerRoute: typeof SellerRouteWithChildren
  CategorySlugRoute: typeof CategorySlugRoute
  LegalDisclaimerRoute: typeof LegalDisclaimerRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalRefundRoute: typeof LegalRefundRoute
  LegalSellerAgreementRoute: typeof LegalSellerAgreementRoute
  LegalTermsRoute: typeof LegalTermsRoute
  ListingSlugRoute: typeof ListingSlugRoute
  ApiPublicRazorpayWebhookRoute: typeof ApiPublicRazorpayWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/seller': {
      id: '/seller'
      path: '/seller'
      fullPath: '/seller'
      preLoaderRoute: typeof SellerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sell': {
      id: '/sell'
      path: '/sell'
      fullPath: '/sell'
      preLoaderRoute: typeof SellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller/': {
      id: '/seller/'
      path: '/'
      fullPath: '/seller/'
      preLoaderRoute: typeof SellerIndexRouteImport
      parentRoute: typeof SellerRoute
    }
    '/messages/': {
      id: '/messages/'
      path: '/'
      fullPath: '/messages/'
      preLoaderRoute: typeof MessagesIndexRouteImport
      parentRoute: typeof MessagesRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/seller/orders': {
      id: '/seller/orders'
      path: '/orders'
      fullPath: '/seller/orders'
      preLoaderRoute: typeof SellerOrdersRouteImport
      parentRoute: typeof SellerRoute
    }
    '/seller/new': {
      id: '/seller/new'
      path: '/new'
      fullPath: '/seller/new'
      preLoaderRoute: typeof SellerNewRouteImport
      parentRoute: typeof SellerRoute
    }
    '/seller/kyc': {
      id: '/seller/kyc'
      path: '/kyc'
      fullPath: '/seller/kyc'
      preLoaderRoute: typeof SellerKycRouteImport
      parentRoute: typeof SellerRoute
    }
    '/seller/$username': {
      id: '/seller/$username'
      path: '/$username'
      fullPath: '/seller/$username'
      preLoaderRoute: typeof SellerUsernameRouteImport
      parentRoute: typeof SellerRoute
    }
    '/messages/$conversationId': {
      id: '/messages/$conversationId'
      path: '/$conversationId'
      fullPath: '/messages/$conversationId'
      preLoaderRoute: typeof MessagesConversationIdRouteImport
      parentRoute: typeof MessagesRoute
    }
    '/listing/$slug': {
      id: '/listing/$slug'
      path: '/listing/$slug'
      fullPath: '/listing/$slug'
      preLoaderRoute: typeof ListingSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/seller-agreement': {
      id: '/legal/seller-agreement'
      path: '/legal/seller-agreement'
      fullPath: '/legal/seller-agreement'
      preLoaderRoute: typeof LegalSellerAgreementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/refund': {
      id: '/legal/refund'
      path: '/legal/refund'
      fullPath: '/legal/refund'
      preLoaderRoute: typeof LegalRefundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/disclaimer': {
      id: '/legal/disclaimer'
      path: '/legal/disclaimer'
      fullPath: '/legal/disclaimer'
      preLoaderRoute: typeof LegalDisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/kyc': {
      id: '/admin/kyc'
      path: '/kyc'
      fullPath: '/admin/kyc'
      preLoaderRoute: typeof AdminKycRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/public/razorpay-webhook': {
      id: '/api/public/razorpay-webhook'
      path: '/api/public/razorpay-webhook'
      fullPath: '/api/public/razorpay-webhook'
      preLoaderRoute: typeof ApiPublicRazorpayWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/orders/$orderId': {
      id: '/admin/orders/$orderId'
      path: '/$orderId'
      fullPath: '/admin/orders/$orderId'
      preLoaderRoute: typeof AdminOrdersOrderIdRouteImport
      parentRoute: typeof AdminOrdersRoute
    }
    '/account/orders/$orderId': {
      id: '/account/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/account/orders/$orderId'
      preLoaderRoute: typeof AccountOrdersOrderIdRouteImport
      parentRoute: typeof AccountRoute
    }
  }
}

interface AccountRouteChildren {
  AccountOrdersOrderIdRoute: typeof AccountOrdersOrderIdRoute
}

const AccountRouteChildren: AccountRouteChildren = {
  AccountOrdersOrderIdRoute: AccountOrdersOrderIdRoute,
}

const AccountRouteWithChildren =
  AccountRoute._addFileChildren(AccountRouteChildren)

interface AdminOrdersRouteChildren {
  AdminOrdersOrderIdRoute: typeof AdminOrdersOrderIdRoute
}

const AdminOrdersRouteChildren: AdminOrdersRouteChildren = {
  AdminOrdersOrderIdRoute: AdminOrdersOrderIdRoute,
}

const AdminOrdersRouteWithChildren = AdminOrdersRoute._addFileChildren(
  AdminOrdersRouteChildren,
)

interface AdminRouteChildren {
  AdminKycRoute: typeof AdminKycRoute
  AdminOrdersRoute: typeof AdminOrdersRouteWithChildren
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminKycRoute: AdminKycRoute,
  AdminOrdersRoute: AdminOrdersRouteWithChildren,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface MessagesRouteChildren {
  MessagesConversationIdRoute: typeof MessagesConversationIdRoute
  MessagesIndexRoute: typeof MessagesIndexRoute
}

const MessagesRouteChildren: MessagesRouteChildren = {
  MessagesConversationIdRoute: MessagesConversationIdRoute,
  MessagesIndexRoute: MessagesIndexRoute,
}

const MessagesRouteWithChildren = MessagesRoute._addFileChildren(
  MessagesRouteChildren,
)

interface SellerRouteChildren {
  SellerUsernameRoute: typeof SellerUsernameRoute
  SellerKycRoute: typeof SellerKycRoute
  SellerNewRoute: typeof SellerNewRoute
  SellerOrdersRoute: typeof SellerOrdersRoute
  SellerIndexRoute: typeof SellerIndexRoute
}

const SellerRouteChildren: SellerRouteChildren = {
  SellerUsernameRoute: SellerUsernameRoute,
  SellerKycRoute: SellerKycRoute,
  SellerNewRoute: SellerNewRoute,
  SellerOrdersRoute: SellerOrdersRoute,
  SellerIndexRoute: SellerIndexRoute,
}

const SellerRouteWithChildren =
  SellerRoute._addFileChildren(SellerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  MarketplaceRoute: MarketplaceRoute,
  MessagesRoute: MessagesRouteWithChildren,
  SellRoute: SellRoute,
  SellerRoute: SellerRouteWithChildren,
  CategorySlugRoute: CategorySlugRoute,
  LegalDisclaimerRoute: LegalDisclaimerRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalRefundRoute: LegalRefundRoute,
  LegalSellerAgreementRoute: LegalSellerAgreementRoute,
  LegalTermsRoute: LegalTermsRoute,
  ListingSlugRoute: ListingSlugRoute,
  ApiPublicRazorpayWebhookRoute: ApiPublicRazorpayWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
